apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: speedtest

resources:
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - gateway.yaml
  - httproute.yaml
  - ciliumnetworkpolicy.yaml

images:
  - name: ghcr.io/librespeed/speedtest
    newTag: latest
